export const CARDS = [
    { suit: 'clubs', value: '9' },
    { suit: 'clubs', value: '10' },
    { suit: 'clubs', value: 'jack' },
    { suit: 'clubs', value: 'queen' },
    { suit: 'clubs', value: 'king' },
    { suit: 'clubs', value: 'ace' },
    { suit: 'hearts', value: '9' },
    { suit: 'hearts', value: '10' },
    { suit: 'hearts', value: 'jack' },
    { suit: 'hearts', value: 'queen' },
    { suit: 'hearts', value: 'king' },
    { suit: 'hearts', value: 'ace' },
    { suit: 'spades', value: '9' },
    { suit: 'spades', value: '10' },
    { suit: 'spades', value: 'jack' },
    { suit: 'spades', value: 'queen' },
    { suit: 'spades', value: 'king' },
    { suit: 'spades', value: 'ace' },
    { suit: 'diamonds', value: '9' },
    { suit: 'diamonds', value: '10' },
    { suit: 'diamonds', value: 'jack' },
    { suit: 'diamonds', value: 'queen' },
    { suit: 'diamonds', value: 'king' },
    { suit: 'diamonds', value: 'ace' },
];
